name: continuous-integration

on: [ pull_request ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
        
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Test
        run: npm test
