name: continuous-integration

on: [ pull_request, push ]

# NOTE: I plan to run a different `release` workflow on `push` events
# when this project is ready to be published to npm

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
        
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Test
        run: npm test
